### ISSUE TITLE
Ambiguity in ICF

### ISSUE THREAD

**Issue by pepol** [Imterra/practices#46]
When parsing ICF in languages that have "true" boolean values, there is a problem with ambiguity of `1` and `0`. The question is if they should be treated as (and converted to) integers or booleans. I believe that it's more natural to treat them like integers. However, this then means problem when user actually wants a boolean value.

With this in mind, I suggest we should remove `1` and `0` from allowed `boolean` values in ICF specification, as well as any implementation.

Would you take a look at this @JakubNvk?

**Comment by JakubNvk** [comment]
@pepol agreed. Let's do this!

**Comment by pepol** [comment]
Fixed by: #47
